### PR TITLE
Include a web_url method to build finished event

### PR DESCRIPTION
**Pull request by eleanorakh**
This PR adds a method so the web URL can be accessed and utilised.

### CODE REVIEW

**Comment by eleanorakh** [comment]
This PR came about as I realised I was unable to access the value for the `web_url` in this PR: https://github.com/conversation/lita-lean_tc/pull/11. Once this is merged, there will be a way to allow the data and the build events to interact so I'll be able to include a specific build URL in the trello card.

**Comment by yob** [comment]
It'd be good to see a spec added to `spec/buildkite_build_finished_event_spec.rb` as well - hopefully the pattern in that file makes the addition easier.

**Comment by eleanorakh** [comment]
yup, I'd committed separately but realised the associated specs should be in same commit. I amended the initial commit to include the specs but normal pushed. I've now force-pushed so the spec addition appears in the same commit as the functionality its describing.

**Review by yob — APPROVED** [review]
:+1:

**Pull request merged**
