### PR TITLE
Prepare 0.3.0 release

### PR DESCRIPTION
**Pull request by nickbrowne**
@yob would you mind adding me as an owner on rubygems? Alternatively please merge this and publish a new version when you get a chance!

Also did you want to join us at Miznon for lunch tomorrow? :smiley:

### CODE REVIEW

**Comment by eleanorakh** [comment]
>Also did you want to join us at Miznon for lunch tomorrow?

It will be delicious and I will probably eat a whole cauliflower.

**Comment by yob** [comment]
@nickbrowne I'll add you to the rubygems project - can you send me the email address to use?

yes, I'm definitely in for lunch. Let me know a time!

**Comment by nickbrowne** [comment]
> can you send me the email address to use?

...good question

**Comment by eleanorakh** [comment]
👌

**Pull request merged**
